'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1

    '''<summary>
    '''ItemCategoryLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ItemCategoryLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ItemCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ItemCategory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ModelLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModelLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Model As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ModelExample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModelExample As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ManufacturerLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManufacturerLable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Manufacturer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Manufacturer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ManufacturerExample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManufacturerExample As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ManufacturerDateLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManufacturerDateLable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MonthLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MonthLable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Month control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Month As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DayLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DayLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DayList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DayList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''YearLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YearLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ManufacturerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManufacturerYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ManufacturerDateExample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManufacturerDateExample As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SerialNumberLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SerialNumberLable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SerialNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SerialNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SerialNumberExample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SerialNumberExample As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DescriptionLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DescriptionLable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Description As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DescriptionExample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DescriptionExample As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddButton As Global.System.Web.UI.WebControls.Button


    '''<summary>
    '''GenerateList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenerateList As Global.System.Web.UI.WebControls.Button

    Protected WithEvents gridview1 As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents CheckBoxList1 As Global.System.Web.UI.WebControls.CheckBoxList

    Protected WithEvents ApproxValue As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents Color As Global.System.Web.UI.WebControls.TextBox

End Class
